const newRooms = [
  {
    title: "Executive Room A",
    imgSrc:
      "https://media.istockphoto.com/id/1323139676/photo/outside-view-of-empty-meeting-room-with-table-and-office-chairs.jpg?s=612x612&w=0&k=20&c=nqEWkNlKAfpdTUl_jiky8YbxiO4jBYcr0gCA5z4MvA0=",
    seatingCapacity: 10,
    amenities: {
      projector: 20,
      "conference call facility": 15,
      whiteboard: 5,
      wifi: 10,
    },
    status: "available",
    isBooked: false,
    bookingEndTime: null,
    members: [],
    duration: 0,
    meetingRoomId: 1,
  },
  {
    title: "Conference Room B",
    imgSrc:
      "https://m.media-amazon.com/images/I/61b9u0Q0uJL._AC_UF894,1000_QL80_.jpg",
    seatingCapacity: 12,
    amenities: {
      tv: 25,
      "coffee machine": 10,
      whiteboard: 5,
      wifi: 10,
    },
    status: "",
    isBooked: true,
    bookingEndTime: new Date(Date.now() + 7200000),
    members: [],
    duration: 0,
    meetingRoomId: 2,
  },
  {
    title: "Boardroom C",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdNKexCUl0f2Jr8-5gSxjGYhhOAbrQnmaavw&s",
    seatingCapacity: 8,
    amenities: {
      projector: 20,
      "conference call facility": 15,
      wifi: 10,
      "water dispenser": 5,
    },
    status: "available",
    isBooked: false,
    bookingEndTime: null,
    members: [],
    duration: 0,
    meetingRoomId: 3,
  },
  {
    title: "Training Room D",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzAXr4DN7tUdc2A0lTrLJ1ZB7tdqKvqzVuWfzSL6uy61Sl7xZww_IOss-Tl1ZToAnfWQE&usqp=CAU",
    seatingCapacity: 20,
    amenities: {
      projector: 20,
      tv: 25,
      wifi: 10,
      whiteboard: 5,
      "coffee machine": 10,
    },
    status: "booked",
    isBooked: true,
    bookingEndTime: new Date(Date.now() + 3600000),
    members: [],
    duration: 0,
    meetingRoomId: 4,
  },
  {
    title: "Meeting Room E",
    imgSrc:
      "https://www.dgicommunications.com/wp-content/uploads/2018/03/DSC_2917.jpg",
    seatingCapacity: 6,
    amenities: {
      projector: 20,
      wifi: 10,
      "water dispenser": 5,
      tv: 25,
    },
    status: "available",
    isBooked: false,
    bookingEndTime: null,
    members: [],
    duration: 0,
    meetingRoomId: 5,
  },
  {
    title: "Huddle Room F",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMT7Hf11Opv4HIbXpHdkIpTkECiqL6kUx_hRrXuOs5RXTZeihrvW8XzkCghhbBheDjP8c&usqp=CAU",
    seatingCapacity: 4,
    amenities: {
      wifi: 10,
      whiteboard: 5,
    },
    status: "available",
    isBooked: false,
    bookingEndTime: null,
    members: [],
    duration: 0,
    meetingRoomId: 6,
  },
  {
    title: "Executive Suite G",
    imgSrc:
      "https://media.istockphoto.com/id/1323139676/photo/outside-view-of-empty-meeting-room-with-table-and-office-chairs.jpg?s=612x612&w=0&k=20&c=nqEWkNlKAfpdTUl_jiky8YbxiO4jBYcr0gCA5z4MvA0=",
    seatingCapacity: 14,
    amenities: {
      projector: 20,
      "conference call facility": 15,
      "coffee machine": 10,
      wifi: 10,
      tv: 25,
    },
    status: "booked",
    isBooked: true,
    bookingEndTime: new Date(Date.now() + 5400000),
    members: [],
    duration: 0,
    meetingRoomId: 7,
  },
  {
    title: "Open Space H",
    imgSrc:
      "https://m.media-amazon.com/images/I/61b9u0Q0uJL._AC_UF894,1000_QL80_.jpg",
    seatingCapacity: 15,
    amenities: {
      wifi: 10,
      whiteboard: 5,
      "water dispenser": 5,
    },
    status: "available",
    isBooked: false,
    bookingEndTime: null,
    members: [],
    duration: 0,
    meetingRoomId: 8,
  },
  {
    title: "Team Room I",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdNKexCUl0f2Jr8-5gSxjGYhhOAbrQnmaavw&s",
    seatingCapacity: 9,
    amenities: {
      projector: 20,
      wifi: 10,
      "coffee machine": 10,
      tv: 25,
    },
    status: "booked",
    isBooked: true,
    bookingEndTime: new Date(Date.now() + 10800000),
    members: [],
    duration: 0,
    meetingRoomId: 9,
  },
  {
    title: "Strategy Room J",
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzAXr4DN7tUdc2A0lTrLJ1ZB7tdqKvqzVuWfzSL6uy61Sl7xZww_IOss-Tl1ZToAnfWQE&usqp=CAU",
    seatingCapacity: 7,
    amenities: {
      "conference call facility": 15,
      wifi: 10,
      whiteboard: 5,
      "water dispenser": 5,
    },
    status: "available",
    isBooked: false,
    bookingEndTime: null,
    members: [],
    duration: 0,
    meetingRoomId: 10,
  },
];

export { newRooms };
